// components/portfolio-section.tsx
import { ReactNode } from 'react';

type Product = {
  tag: string;
  name: string;
  description: string;
  proof?: ReactNode;
  href: string;
  cta: string;
};

const Gold = ({ children }: { children: ReactNode }) => (
  <span className="text-accent-gold font-bold">{children}</span>
);

const products: Product[] = [
  {
    tag: 'Manufacturing',
    name: 'LoomWorks',
    description:
      'A complete manufacturing ERP — production tracking, yarn accounting, financial reconciliation, and daily AI briefings for a 27-loom textile operation.',
    proof: (
      <>
        Built on a production system that replaced <Gold>5</Gold> employees and
        eliminated <Gold>40+</Gold> hours of weekly manual work. Live for{' '}
        <Gold>10+</Gold> months.
      </>
    ),
    href: 'https://loomworks.vanthrope.com',
    cta: 'Open LoomWorks →',
  },
  {
    tag: 'Ecommerce',
    name: 'BrandPilot',
    description:
      'An ecommerce command center — revenue, inventory, SEO, content, and finance across Shopify and Amazon in one screen, with an AI morning brief that tells you exactly what needs attention today.',
    proof: <>Built on the operational stack running a live multi-market ecommerce brand.</>,
    href: 'https://brandpilot.vanthrope.com',
    cta: 'Open BrandPilot →',
  },
  {
    tag: 'Market Intelligence',
    name: 'MarketLens',
    description:
      'An AI-powered market terminal — live charts, portfolio tracking, and Warren, an AI analyst that answers market questions in plain language.',
    href: 'https://marketlens.vanthrope.com',
    cta: 'Open MarketLens →',
  },
  {
    tag: 'Legal',
    name: 'Legality AI',
    description:
      'Consulting agreements and legal documents drafted in minutes — generated by AI, reviewed by you, downloaded as PDF.',
    href: 'https://legality.vanthrope.com',
    cta: 'Open Legality AI →',
  },
];

export default function PortfolioSection() {
  return (
    <section id="proof" className="bg-bg-primary py-20 md:py-32 scroll-mt-16">
      <div className="max-w-6xl mx-auto px-6">
        <span className="block text-xs font-semibold tracking-[0.2em] uppercase text-accent-gold mb-4">
          The Proof
        </span>
        <h2 className="text-3xl md:text-4xl font-black tracking-tight text-text-primary leading-tight">
          Live products. Real systems. Use them yourself.
        </h2>
        <p className="text-base md:text-lg text-text-muted leading-relaxed max-w-2xl mt-6 mb-12">
          Most portfolios show screenshots. These are working products — open them,
          click around, ask their built-in AI assistants anything.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {products.map((product) => (
            <div
              key={product.name}
              className="bg-bg-secondary border border-border-color hover:border-border-gold rounded-2xl p-6 md:p-8 flex flex-col transition-colors duration-200"
            >
              <span className="text-xs uppercase tracking-widest text-accent-gold bg-accent-gold-dim px-3 py-1 rounded-full w-fit">
                {product.tag}
              </span>

              <h3 className="text-lg md:text-xl font-bold text-text-primary mt-4">
                {product.name}
              </h3>

              <p className="text-base text-text-muted leading-relaxed mt-3 flex-grow">
                {product.description}
              </p>

              {product.proof && (
                <p className="text-sm text-text-muted leading-relaxed mt-4">
                  {product.proof}
                </p>
              )}

              <a
                href={product.href}
                target="_blank"
                rel="noopener noreferrer"
                className="text-accent-gold hover:text-accent-gold-hover hover:underline underline-offset-4 text-sm font-semibold mt-6 transition-colors duration-200"
                style={{ minHeight: '44px', display: 'inline-flex', alignItems: 'center' }}
              >
                {product.cta}
              </a>
            </div>
          ))}
        </div>

        <p className="text-sm text-text-subtle max-w-2xl mt-8">
          The production systems behind LoomWorks and BrandPilot run on real
          business data. They are demonstrated live on calls.
        </p>
      </div>
    </section>
  );
}
