// app/terms/page.tsx
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms & Conditions | Arslan Rehmani',
  description: 'Terms and Conditions governing the use of arslanrehmani.com, tool outputs, and consulting services.',
  alternates: {
    canonical: '/terms',
  },
  openGraph: {
    title: 'Terms & Conditions | Arslan Rehmani',
    description: 'Terms and Conditions for arslanrehmani.com.',
    url: 'https://arslanrehmani.com/terms',
    siteName: 'Arslan Rehmani',
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary',
    title: 'Terms & Conditions | Arslan Rehmani',
    description: 'Terms and Conditions for arslanrehmani.com.',
  },
};

export default function TermsPage() {
  return (
    <main className="bg-bg-primary min-h-screen py-16 md:py-28">
      <div className="max-w-4xl mx-auto px-6">
        <span className="eyebrow mb-4">Legal & Compliance</span>
        <h1 className="headline text-3xl md:text-5xl leading-[1.1] mb-4">
          Terms & Conditions
        </h1>
        <p className="text-sm text-text-subtle mb-12">
          Last Updated: July 30, 2026
        </p>

        <div className="space-y-10 text-text-muted leading-relaxed text-base border-t border-border-color pt-10">
          {/* ========================================================================= */}
          {/* LEGAL PLACEHOLDER SECTION START — TO BE REPLACED WITH FINALIZED LEGAL COPY */}
          {/* ========================================================================= */}

          <div className="p-6 bg-bg-secondary border border-border-gold/40 rounded-2xl">
            <span className="text-xs font-bold text-accent-gold uppercase tracking-wider block mb-2">
              Production Placeholder Notice
            </span>
            <p className="text-xs text-text-muted leading-relaxed">
              This page outlines the general terms governing website access and interactive tool usage on arslanrehmani.com. Formal commercial terms for custom software builds are governed under separate client service agreements.
            </p>
          </div>

          <section>
            <h2 className="text-xl font-bold text-text-primary mb-3">1. Acceptance of Terms</h2>
            {/* <!-- PLACEHOLDER: Insert detailed Acceptance of Terms clause here --> */}
            <p>
              By accessing and using arslanrehmani.com and its associated interactive tools (including the AI Readiness Audit and ROI Calculator), you agree to comply with and be bound by these Terms & Conditions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-text-primary mb-3">2. Intellectual Property</h2>
            {/* <!-- PLACEHOLDER: Insert detailed Intellectual Property rights here --> */}
            <p>
              All software architectures, case study analysis, operational frameworks, original text, and branding presented on this website are the property of Arslan Rehmani. Live client demonstrations (such as TextileMode ERP and Belhide Operational Stack) are presented for proof purposes under client authorization.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-text-primary mb-3">3. Interactive Tool Outputs & Estimates</h2>
            {/* <!-- PLACEHOLDER: Insert Limitation of Liability regarding tool outputs here --> */}
            <p>
              Estimates generated by website calculators or audit tools are provided for informational and preliminary assessment purposes only. Formal financial ROI and operational impact commitments are established through custom scoping audits.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-text-primary mb-3">4. Inquiries & Contact</h2>
            {/* <!-- PLACEHOLDER: Insert Legal Contact information here --> */}
            <p>
              For legal inquiries regarding these terms, please contact{' '}
              <a href="mailto:contact@arslanrehmani.com" className="text-accent-gold hover:underline font-mono">
                contact@arslanrehmani.com
              </a>.
            </p>
          </section>

          {/* ========================================================================= */}
          {/* LEGAL PLACEHOLDER SECTION END */}
          {/* ========================================================================= */}
        </div>

        <div className="mt-16 pt-8 border-t border-border-color">
          <Link href="/contact" className="btn-ghost !text-xs">
            Return to Contact →
          </Link>
        </div>
      </div>
    </main>
  );
}
